version: '3.8'

services:
  api:
    build: .
    container_name: fpf_api
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    restart: unless-stopped
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload


